services:
  postgres:
    image: postgres:18-alpine
    container_name: archypix-back-db
    environment:
      POSTGRES_DB: archypix_back
      POSTGRES_USER: archypix
      POSTGRES_PASSWORD: archypix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U archypix" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
